//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("xmaslistlegacyModel", "fk_er_ev_key", "Event", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(GiftList.Event), "EventRecip", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(GiftList.EventRecip), true)]
[assembly: EdmRelationshipAttribute("xmaslistlegacyModel", "fk_er_rp_key", "recipient", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(GiftList.recipient), "EventRecip", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(GiftList.EventRecip), true)]
[assembly: EdmRelationshipAttribute("xmaslistlegacyModel", "fk_ev_fm_key", "Family", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(GiftList.Family), "Event", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(GiftList.Event), true)]
[assembly: EdmRelationshipAttribute("xmaslistlegacyModel", "fk_ev_tm_key", "theme", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(GiftList.theme), "Event", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(GiftList.Event), true)]
[assembly: EdmRelationshipAttribute("xmaslistlegacyModel", "fk_rp_fm_key", "Family", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(GiftList.Family), "recipient", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(GiftList.recipient), true)]
[assembly: EdmRelationshipAttribute("xmaslistlegacyModel", "fk_ll_rp_key", "recipient", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(GiftList.recipient), "LogonLog", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(GiftList.LogonLog), true)]
[assembly: EdmRelationshipAttribute("xmaslistlegacyModel", "fk_li_Author", "recipient", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(GiftList.recipient), "lists", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(GiftList.lists), true)]
[assembly: EdmRelationshipAttribute("xmaslistlegacyModel", "fk_li_HideFrom", "recipient", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(GiftList.recipient), "lists", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(GiftList.lists), true)]
[assembly: EdmRelationshipAttribute("xmaslistlegacyModel", "fk_li_rp_key", "recipient", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(GiftList.recipient), "lists", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(GiftList.lists), true)]
[assembly: EdmRelationshipAttribute("xmaslistlegacyModel", "fk_li_takenby", "recipient", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(GiftList.recipient), "lists", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(GiftList.lists), true)]

#endregion

namespace GiftList
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class xmaslistlegacyEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new xmaslistlegacyEntities object using the connection string found in the 'xmaslistlegacyEntities' section of the application configuration file.
        /// </summary>
        public xmaslistlegacyEntities() : base("name=xmaslistlegacyEntities", "xmaslistlegacyEntities")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new xmaslistlegacyEntities object.
        /// </summary>
        public xmaslistlegacyEntities(string connectionString) : base(connectionString, "xmaslistlegacyEntities")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new xmaslistlegacyEntities object.
        /// </summary>
        public xmaslistlegacyEntities(EntityConnection connection) : base(connection, "xmaslistlegacyEntities")
        {
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<EventRecip> EventRecips
        {
            get
            {
                if ((_EventRecips == null))
                {
                    _EventRecips = base.CreateObjectSet<EventRecip>("EventRecips");
                }
                return _EventRecips;
            }
        }
        private ObjectSet<EventRecip> _EventRecips;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Event> Events
        {
            get
            {
                if ((_Events == null))
                {
                    _Events = base.CreateObjectSet<Event>("Events");
                }
                return _Events;
            }
        }
        private ObjectSet<Event> _Events;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Family> Families
        {
            get
            {
                if ((_Families == null))
                {
                    _Families = base.CreateObjectSet<Family>("Families");
                }
                return _Families;
            }
        }
        private ObjectSet<Family> _Families;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<recipient> recipients
        {
            get
            {
                if ((_recipients == null))
                {
                    _recipients = base.CreateObjectSet<recipient>("recipients");
                }
                return _recipients;
            }
        }
        private ObjectSet<recipient> _recipients;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<theme> themes
        {
            get
            {
                if ((_themes == null))
                {
                    _themes = base.CreateObjectSet<theme>("themes");
                }
                return _themes;
            }
        }
        private ObjectSet<theme> _themes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<LogonLog> LogonLog
        {
            get
            {
                if ((_LogonLog == null))
                {
                    _LogonLog = base.CreateObjectSet<LogonLog>("LogonLog");
                }
                return _LogonLog;
            }
        }
        private ObjectSet<LogonLog> _LogonLog;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<lists> lists
        {
            get
            {
                if ((_lists == null))
                {
                    _lists = base.CreateObjectSet<lists>("lists");
                }
                return _lists;
            }
        }
        private ObjectSet<lists> _lists;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the EventRecips EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEventRecips(EventRecip eventRecip)
        {
            base.AddObject("EventRecips", eventRecip);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Events EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEvents(Event @event)
        {
            base.AddObject("Events", @event);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Families EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFamilies(Family family)
        {
            base.AddObject("Families", family);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the recipients EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTorecipients(recipient recipient)
        {
            base.AddObject("recipients", recipient);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the themes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTothemes(theme theme)
        {
            base.AddObject("themes", theme);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the LogonLog EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLogonLog(LogonLog logonLog)
        {
            base.AddObject("LogonLog", logonLog);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the lists EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTolists(lists lists)
        {
            base.AddObject("lists", lists);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="xmaslistlegacyModel", Name="Event")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Event : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Event object.
        /// </summary>
        /// <param name="ev_key">Initial value of the ev_key property.</param>
        /// <param name="ev_desc">Initial value of the ev_desc property.</param>
        /// <param name="ev_date">Initial value of the ev_date property.</param>
        /// <param name="ev_fm_key">Initial value of the ev_fm_key property.</param>
        /// <param name="ev_tm_key">Initial value of the ev_tm_key property.</param>
        public static Event CreateEvent(global::System.Int32 ev_key, global::System.String ev_desc, global::System.DateTime ev_date, global::System.Int32 ev_fm_key, global::System.Int32 ev_tm_key)
        {
            Event @event = new Event();
            @event.ev_key = ev_key;
            @event.ev_desc = ev_desc;
            @event.ev_date = ev_date;
            @event.ev_fm_key = ev_fm_key;
            @event.ev_tm_key = ev_tm_key;
            return @event;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ev_key
        {
            get
            {
                return _ev_key;
            }
            set
            {
                if (_ev_key != value)
                {
                    Onev_keyChanging(value);
                    ReportPropertyChanging("ev_key");
                    _ev_key = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ev_key");
                    Onev_keyChanged();
                }
            }
        }
        private global::System.Int32 _ev_key;
        partial void Onev_keyChanging(global::System.Int32 value);
        partial void Onev_keyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ev_desc
        {
            get
            {
                return _ev_desc;
            }
            set
            {
                Onev_descChanging(value);
                ReportPropertyChanging("ev_desc");
                _ev_desc = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ev_desc");
                Onev_descChanged();
            }
        }
        private global::System.String _ev_desc;
        partial void Onev_descChanging(global::System.String value);
        partial void Onev_descChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime ev_date
        {
            get
            {
                return _ev_date;
            }
            set
            {
                Onev_dateChanging(value);
                ReportPropertyChanging("ev_date");
                _ev_date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ev_date");
                Onev_dateChanged();
            }
        }
        private global::System.DateTime _ev_date;
        partial void Onev_dateChanging(global::System.DateTime value);
        partial void Onev_dateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ev_fm_key
        {
            get
            {
                return _ev_fm_key;
            }
            set
            {
                Onev_fm_keyChanging(value);
                ReportPropertyChanging("ev_fm_key");
                _ev_fm_key = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ev_fm_key");
                Onev_fm_keyChanged();
            }
        }
        private global::System.Int32 _ev_fm_key;
        partial void Onev_fm_keyChanging(global::System.Int32 value);
        partial void Onev_fm_keyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ev_tm_key
        {
            get
            {
                return _ev_tm_key;
            }
            set
            {
                Onev_tm_keyChanging(value);
                ReportPropertyChanging("ev_tm_key");
                _ev_tm_key = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ev_tm_key");
                Onev_tm_keyChanged();
            }
        }
        private global::System.Int32 _ev_tm_key;
        partial void Onev_tm_keyChanging(global::System.Int32 value);
        partial void Onev_tm_keyChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("xmaslistlegacyModel", "fk_er_ev_key", "EventRecip")]
        public EntityCollection<EventRecip> EventRecips
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<EventRecip>("xmaslistlegacyModel.fk_er_ev_key", "EventRecip");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<EventRecip>("xmaslistlegacyModel.fk_er_ev_key", "EventRecip", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("xmaslistlegacyModel", "fk_ev_fm_key", "Family")]
        public Family Family
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Family>("xmaslistlegacyModel.fk_ev_fm_key", "Family").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Family>("xmaslistlegacyModel.fk_ev_fm_key", "Family").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Family> FamilyReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Family>("xmaslistlegacyModel.fk_ev_fm_key", "Family");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Family>("xmaslistlegacyModel.fk_ev_fm_key", "Family", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("xmaslistlegacyModel", "fk_ev_tm_key", "theme")]
        public theme theme
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<theme>("xmaslistlegacyModel.fk_ev_tm_key", "theme").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<theme>("xmaslistlegacyModel.fk_ev_tm_key", "theme").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<theme> themeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<theme>("xmaslistlegacyModel.fk_ev_tm_key", "theme");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<theme>("xmaslistlegacyModel.fk_ev_tm_key", "theme", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="xmaslistlegacyModel", Name="EventRecip")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class EventRecip : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new EventRecip object.
        /// </summary>
        /// <param name="er_key">Initial value of the er_key property.</param>
        /// <param name="er_rp_key">Initial value of the er_rp_key property.</param>
        /// <param name="er_ev_key">Initial value of the er_ev_key property.</param>
        public static EventRecip CreateEventRecip(global::System.Int32 er_key, global::System.Int32 er_rp_key, global::System.Int32 er_ev_key)
        {
            EventRecip eventRecip = new EventRecip();
            eventRecip.er_key = er_key;
            eventRecip.er_rp_key = er_rp_key;
            eventRecip.er_ev_key = er_ev_key;
            return eventRecip;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 er_key
        {
            get
            {
                return _er_key;
            }
            set
            {
                if (_er_key != value)
                {
                    Oner_keyChanging(value);
                    ReportPropertyChanging("er_key");
                    _er_key = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("er_key");
                    Oner_keyChanged();
                }
            }
        }
        private global::System.Int32 _er_key;
        partial void Oner_keyChanging(global::System.Int32 value);
        partial void Oner_keyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 er_rp_key
        {
            get
            {
                return _er_rp_key;
            }
            set
            {
                Oner_rp_keyChanging(value);
                ReportPropertyChanging("er_rp_key");
                _er_rp_key = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("er_rp_key");
                Oner_rp_keyChanged();
            }
        }
        private global::System.Int32 _er_rp_key;
        partial void Oner_rp_keyChanging(global::System.Int32 value);
        partial void Oner_rp_keyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 er_ev_key
        {
            get
            {
                return _er_ev_key;
            }
            set
            {
                Oner_ev_keyChanging(value);
                ReportPropertyChanging("er_ev_key");
                _er_ev_key = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("er_ev_key");
                Oner_ev_keyChanged();
            }
        }
        private global::System.Int32 _er_ev_key;
        partial void Oner_ev_keyChanging(global::System.Int32 value);
        partial void Oner_ev_keyChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("xmaslistlegacyModel", "fk_er_ev_key", "Event")]
        public Event Event
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Event>("xmaslistlegacyModel.fk_er_ev_key", "Event").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Event>("xmaslistlegacyModel.fk_er_ev_key", "Event").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Event> EventReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Event>("xmaslistlegacyModel.fk_er_ev_key", "Event");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Event>("xmaslistlegacyModel.fk_er_ev_key", "Event", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("xmaslistlegacyModel", "fk_er_rp_key", "recipient")]
        public recipient recipient
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<recipient>("xmaslistlegacyModel.fk_er_rp_key", "recipient").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<recipient>("xmaslistlegacyModel.fk_er_rp_key", "recipient").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<recipient> recipientReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<recipient>("xmaslistlegacyModel.fk_er_rp_key", "recipient");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<recipient>("xmaslistlegacyModel.fk_er_rp_key", "recipient", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="xmaslistlegacyModel", Name="Family")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Family : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Family object.
        /// </summary>
        /// <param name="fm_key">Initial value of the fm_key property.</param>
        /// <param name="fm_name">Initial value of the fm_name property.</param>
        /// <param name="fm_url">Initial value of the fm_url property.</param>
        /// <param name="fm_admin_rp_key">Initial value of the fm_admin_rp_key property.</param>
        public static Family CreateFamily(global::System.Int32 fm_key, global::System.String fm_name, global::System.String fm_url, global::System.Int32 fm_admin_rp_key)
        {
            Family family = new Family();
            family.fm_key = fm_key;
            family.fm_name = fm_name;
            family.fm_url = fm_url;
            family.fm_admin_rp_key = fm_admin_rp_key;
            return family;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 fm_key
        {
            get
            {
                return _fm_key;
            }
            set
            {
                if (_fm_key != value)
                {
                    Onfm_keyChanging(value);
                    ReportPropertyChanging("fm_key");
                    _fm_key = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("fm_key");
                    Onfm_keyChanged();
                }
            }
        }
        private global::System.Int32 _fm_key;
        partial void Onfm_keyChanging(global::System.Int32 value);
        partial void Onfm_keyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String fm_name
        {
            get
            {
                return _fm_name;
            }
            set
            {
                Onfm_nameChanging(value);
                ReportPropertyChanging("fm_name");
                _fm_name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("fm_name");
                Onfm_nameChanged();
            }
        }
        private global::System.String _fm_name;
        partial void Onfm_nameChanging(global::System.String value);
        partial void Onfm_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String fm_url
        {
            get
            {
                return _fm_url;
            }
            set
            {
                Onfm_urlChanging(value);
                ReportPropertyChanging("fm_url");
                _fm_url = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("fm_url");
                Onfm_urlChanged();
            }
        }
        private global::System.String _fm_url;
        partial void Onfm_urlChanging(global::System.String value);
        partial void Onfm_urlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 fm_admin_rp_key
        {
            get
            {
                return _fm_admin_rp_key;
            }
            set
            {
                Onfm_admin_rp_keyChanging(value);
                ReportPropertyChanging("fm_admin_rp_key");
                _fm_admin_rp_key = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fm_admin_rp_key");
                Onfm_admin_rp_keyChanged();
            }
        }
        private global::System.Int32 _fm_admin_rp_key;
        partial void Onfm_admin_rp_keyChanging(global::System.Int32 value);
        partial void Onfm_admin_rp_keyChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("xmaslistlegacyModel", "fk_ev_fm_key", "Event")]
        public EntityCollection<Event> Events
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Event>("xmaslistlegacyModel.fk_ev_fm_key", "Event");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Event>("xmaslistlegacyModel.fk_ev_fm_key", "Event", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("xmaslistlegacyModel", "fk_rp_fm_key", "recipient")]
        public EntityCollection<recipient> recipients
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<recipient>("xmaslistlegacyModel.fk_rp_fm_key", "recipient");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<recipient>("xmaslistlegacyModel.fk_rp_fm_key", "recipient", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="xmaslistlegacyModel", Name="lists")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class lists : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new lists object.
        /// </summary>
        /// <param name="li_key">Initial value of the li_key property.</param>
        /// <param name="li_rp_key">Initial value of the li_rp_key property.</param>
        /// <param name="li_title">Initial value of the li_title property.</param>
        /// <param name="li_desc">Initial value of the li_desc property.</param>
        /// <param name="li_year">Initial value of the li_year property.</param>
        /// <param name="li_author">Initial value of the li_author property.</param>
        /// <param name="li_aquired">Initial value of the li_aquired property.</param>
        /// <param name="li_url">Initial value of the li_url property.</param>
        /// <param name="li_Size">Initial value of the li_Size property.</param>
        /// <param name="li_Color">Initial value of the li_Color property.</param>
        /// <param name="li_CreateDate">Initial value of the li_CreateDate property.</param>
        /// <param name="li_TouchDate">Initial value of the li_TouchDate property.</param>
        /// <param name="li_Archive">Initial value of the li_Archive property.</param>
        public static lists Createlists(global::System.Int32 li_key, global::System.Int32 li_rp_key, global::System.String li_title, global::System.String li_desc, global::System.String li_year, global::System.Int32 li_author, global::System.Byte li_aquired, global::System.String li_url, global::System.String li_Size, global::System.String li_Color, global::System.DateTime li_CreateDate, global::System.DateTime li_TouchDate, global::System.Byte li_Archive)
        {
            lists lists = new lists();
            lists.li_key = li_key;
            lists.li_rp_key = li_rp_key;
            lists.li_title = li_title;
            lists.li_desc = li_desc;
            lists.li_year = li_year;
            lists.li_author = li_author;
            lists.li_aquired = li_aquired;
            lists.li_url = li_url;
            lists.li_Size = li_Size;
            lists.li_Color = li_Color;
            lists.li_CreateDate = li_CreateDate;
            lists.li_TouchDate = li_TouchDate;
            lists.li_Archive = li_Archive;
            return lists;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 li_key
        {
            get
            {
                return _li_key;
            }
            set
            {
                if (_li_key != value)
                {
                    Onli_keyChanging(value);
                    ReportPropertyChanging("li_key");
                    _li_key = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("li_key");
                    Onli_keyChanged();
                }
            }
        }
        private global::System.Int32 _li_key;
        partial void Onli_keyChanging(global::System.Int32 value);
        partial void Onli_keyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 li_rp_key
        {
            get
            {
                return _li_rp_key;
            }
            set
            {
                Onli_rp_keyChanging(value);
                ReportPropertyChanging("li_rp_key");
                _li_rp_key = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("li_rp_key");
                Onli_rp_keyChanged();
            }
        }
        private global::System.Int32 _li_rp_key;
        partial void Onli_rp_keyChanging(global::System.Int32 value);
        partial void Onli_rp_keyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String li_title
        {
            get
            {
                return _li_title;
            }
            set
            {
                Onli_titleChanging(value);
                ReportPropertyChanging("li_title");
                _li_title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("li_title");
                Onli_titleChanged();
            }
        }
        private global::System.String _li_title;
        partial void Onli_titleChanging(global::System.String value);
        partial void Onli_titleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String li_desc
        {
            get
            {
                return _li_desc;
            }
            set
            {
                Onli_descChanging(value);
                ReportPropertyChanging("li_desc");
                _li_desc = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("li_desc");
                Onli_descChanged();
            }
        }
        private global::System.String _li_desc;
        partial void Onli_descChanging(global::System.String value);
        partial void Onli_descChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> li_takenby
        {
            get
            {
                return _li_takenby;
            }
            set
            {
                Onli_takenbyChanging(value);
                ReportPropertyChanging("li_takenby");
                _li_takenby = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("li_takenby");
                Onli_takenbyChanged();
            }
        }
        private Nullable<global::System.Int32> _li_takenby;
        partial void Onli_takenbyChanging(Nullable<global::System.Int32> value);
        partial void Onli_takenbyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String li_year
        {
            get
            {
                return _li_year;
            }
            set
            {
                Onli_yearChanging(value);
                ReportPropertyChanging("li_year");
                _li_year = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("li_year");
                Onli_yearChanged();
            }
        }
        private global::System.String _li_year;
        partial void Onli_yearChanging(global::System.String value);
        partial void Onli_yearChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> li_hidefrom
        {
            get
            {
                return _li_hidefrom;
            }
            set
            {
                Onli_hidefromChanging(value);
                ReportPropertyChanging("li_hidefrom");
                _li_hidefrom = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("li_hidefrom");
                Onli_hidefromChanged();
            }
        }
        private Nullable<global::System.Int32> _li_hidefrom;
        partial void Onli_hidefromChanging(Nullable<global::System.Int32> value);
        partial void Onli_hidefromChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 li_author
        {
            get
            {
                return _li_author;
            }
            set
            {
                Onli_authorChanging(value);
                ReportPropertyChanging("li_author");
                _li_author = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("li_author");
                Onli_authorChanged();
            }
        }
        private global::System.Int32 _li_author;
        partial void Onli_authorChanging(global::System.Int32 value);
        partial void Onli_authorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte li_aquired
        {
            get
            {
                return _li_aquired;
            }
            set
            {
                Onli_aquiredChanging(value);
                ReportPropertyChanging("li_aquired");
                _li_aquired = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("li_aquired");
                Onli_aquiredChanged();
            }
        }
        private global::System.Byte _li_aquired;
        partial void Onli_aquiredChanging(global::System.Byte value);
        partial void Onli_aquiredChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String li_url
        {
            get
            {
                return _li_url;
            }
            set
            {
                Onli_urlChanging(value);
                ReportPropertyChanging("li_url");
                _li_url = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("li_url");
                Onli_urlChanged();
            }
        }
        private global::System.String _li_url;
        partial void Onli_urlChanging(global::System.String value);
        partial void Onli_urlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String li_Size
        {
            get
            {
                return _li_Size;
            }
            set
            {
                Onli_SizeChanging(value);
                ReportPropertyChanging("li_Size");
                _li_Size = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("li_Size");
                Onli_SizeChanged();
            }
        }
        private global::System.String _li_Size;
        partial void Onli_SizeChanging(global::System.String value);
        partial void Onli_SizeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String li_Color
        {
            get
            {
                return _li_Color;
            }
            set
            {
                Onli_ColorChanging(value);
                ReportPropertyChanging("li_Color");
                _li_Color = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("li_Color");
                Onli_ColorChanged();
            }
        }
        private global::System.String _li_Color;
        partial void Onli_ColorChanging(global::System.String value);
        partial void Onli_ColorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime li_CreateDate
        {
            get
            {
                return _li_CreateDate;
            }
            set
            {
                Onli_CreateDateChanging(value);
                ReportPropertyChanging("li_CreateDate");
                _li_CreateDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("li_CreateDate");
                Onli_CreateDateChanged();
            }
        }
        private global::System.DateTime _li_CreateDate;
        partial void Onli_CreateDateChanging(global::System.DateTime value);
        partial void Onli_CreateDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime li_TouchDate
        {
            get
            {
                return _li_TouchDate;
            }
            set
            {
                Onli_TouchDateChanging(value);
                ReportPropertyChanging("li_TouchDate");
                _li_TouchDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("li_TouchDate");
                Onli_TouchDateChanged();
            }
        }
        private global::System.DateTime _li_TouchDate;
        partial void Onli_TouchDateChanging(global::System.DateTime value);
        partial void Onli_TouchDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String li_GiverComment
        {
            get
            {
                return _li_GiverComment;
            }
            set
            {
                Onli_GiverCommentChanging(value);
                ReportPropertyChanging("li_GiverComment");
                _li_GiverComment = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("li_GiverComment");
                Onli_GiverCommentChanged();
            }
        }
        private global::System.String _li_GiverComment;
        partial void Onli_GiverCommentChanging(global::System.String value);
        partial void Onli_GiverCommentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte li_Archive
        {
            get
            {
                return _li_Archive;
            }
            set
            {
                Onli_ArchiveChanging(value);
                ReportPropertyChanging("li_Archive");
                _li_Archive = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("li_Archive");
                Onli_ArchiveChanged();
            }
        }
        private global::System.Byte _li_Archive;
        partial void Onli_ArchiveChanging(global::System.Int16 value);
        partial void Onli_ArchiveChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("xmaslistlegacyModel", "fk_li_Author", "recipient")]
        public recipient Author
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<recipient>("xmaslistlegacyModel.fk_li_Author", "recipient").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<recipient>("xmaslistlegacyModel.fk_li_Author", "recipient").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<recipient> AuthorReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<recipient>("xmaslistlegacyModel.fk_li_Author", "recipient");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<recipient>("xmaslistlegacyModel.fk_li_Author", "recipient", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("xmaslistlegacyModel", "fk_li_HideFrom", "recipient")]
        public recipient HideFrom
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<recipient>("xmaslistlegacyModel.fk_li_HideFrom", "recipient").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<recipient>("xmaslistlegacyModel.fk_li_HideFrom", "recipient").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<recipient> HideFromReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<recipient>("xmaslistlegacyModel.fk_li_HideFrom", "recipient");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<recipient>("xmaslistlegacyModel.fk_li_HideFrom", "recipient", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("xmaslistlegacyModel", "fk_li_rp_key", "recipient")]
        public recipient Recipient
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<recipient>("xmaslistlegacyModel.fk_li_rp_key", "recipient").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<recipient>("xmaslistlegacyModel.fk_li_rp_key", "recipient").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<recipient> RecipientReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<recipient>("xmaslistlegacyModel.fk_li_rp_key", "recipient");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<recipient>("xmaslistlegacyModel.fk_li_rp_key", "recipient", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("xmaslistlegacyModel", "fk_li_takenby", "recipient")]
        public recipient TakenBy
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<recipient>("xmaslistlegacyModel.fk_li_takenby", "recipient").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<recipient>("xmaslistlegacyModel.fk_li_takenby", "recipient").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<recipient> TakenByReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<recipient>("xmaslistlegacyModel.fk_li_takenby", "recipient");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<recipient>("xmaslistlegacyModel.fk_li_takenby", "recipient", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="xmaslistlegacyModel", Name="LogonLog")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class LogonLog : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new LogonLog object.
        /// </summary>
        /// <param name="ll_LogonLog_Key">Initial value of the ll_LogonLog_Key property.</param>
        /// <param name="ll_rp_key">Initial value of the ll_rp_key property.</param>
        /// <param name="ll_sid">Initial value of the ll_sid property.</param>
        public static LogonLog CreateLogonLog(global::System.Int32 ll_LogonLog_Key, global::System.Int32 ll_rp_key, global::System.Guid ll_sid)
        {
            LogonLog logonLog = new LogonLog();
            logonLog.ll_LogonLog_Key = ll_LogonLog_Key;
            logonLog.ll_rp_key = ll_rp_key;
            logonLog.ll_sid = ll_sid;
            return logonLog;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ll_LogonLog_Key
        {
            get
            {
                return _ll_LogonLog_Key;
            }
            set
            {
                if (_ll_LogonLog_Key != value)
                {
                    Onll_LogonLog_KeyChanging(value);
                    ReportPropertyChanging("ll_LogonLog_Key");
                    _ll_LogonLog_Key = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ll_LogonLog_Key");
                    Onll_LogonLog_KeyChanged();
                }
            }
        }
        private global::System.Int32 _ll_LogonLog_Key;
        partial void Onll_LogonLog_KeyChanging(global::System.Int32 value);
        partial void Onll_LogonLog_KeyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ll_rp_key
        {
            get
            {
                return _ll_rp_key;
            }
            set
            {
                Onll_rp_keyChanging(value);
                ReportPropertyChanging("ll_rp_key");
                _ll_rp_key = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ll_rp_key");
                Onll_rp_keyChanged();
            }
        }
        private global::System.Int32 _ll_rp_key;
        partial void Onll_rp_keyChanging(global::System.Int32 value);
        partial void Onll_rp_keyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid ll_sid
        {
            get
            {
                return _ll_sid;
            }
            set
            {
                Onll_sidChanging(value);
                ReportPropertyChanging("ll_sid");
                _ll_sid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ll_sid");
                Onll_sidChanged();
            }
        }
        private global::System.Guid _ll_sid;
        partial void Onll_sidChanging(global::System.Guid value);
        partial void Onll_sidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ll_Create_Date
        {
            get
            {
                return _ll_Create_Date;
            }
            set
            {
                Onll_Create_DateChanging(value);
                ReportPropertyChanging("ll_Create_Date");
                _ll_Create_Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ll_Create_Date");
                Onll_Create_DateChanged();
            }
        }
        private Nullable<global::System.DateTime> _ll_Create_Date;
        partial void Onll_Create_DateChanging(Nullable<global::System.DateTime> value);
        partial void Onll_Create_DateChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("xmaslistlegacyModel", "fk_ll_rp_key", "recipient")]
        public recipient recipients
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<recipient>("xmaslistlegacyModel.fk_ll_rp_key", "recipient").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<recipient>("xmaslistlegacyModel.fk_ll_rp_key", "recipient").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<recipient> recipientsReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<recipient>("xmaslistlegacyModel.fk_ll_rp_key", "recipient");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<recipient>("xmaslistlegacyModel.fk_ll_rp_key", "recipient", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="xmaslistlegacyModel", Name="recipient")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class recipient : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new recipient object.
        /// </summary>
        /// <param name="rp_key">Initial value of the rp_key property.</param>
        /// <param name="rp_lastname">Initial value of the rp_lastname property.</param>
        /// <param name="rp_password">Initial value of the rp_password property.</param>
        /// <param name="rp_background">Initial value of the rp_background property.</param>
        /// <param name="rp_sound">Initial value of the rp_sound property.</param>
        /// <param name="rp_firstname">Initial value of the rp_firstname property.</param>
        /// <param name="rp_email">Initial value of the rp_email property.</param>
        /// <param name="rp_fm_key">Initial value of the rp_fm_key property.</param>
        /// <param name="rp_recipient">Initial value of the rp_recipient property.</param>
        /// <param name="rp_giver">Initial value of the rp_giver property.</param>
        /// /// <param name="rp_Archive">Initial value of the rp_Archive property.</param>
        public static recipient Createrecipient(global::System.Int32 rp_key, global::System.String rp_lastname, global::System.String rp_password, global::System.String rp_background, global::System.String rp_sound, global::System.String rp_firstname, global::System.String rp_email, global::System.Int32 rp_fm_key, global::System.Byte rp_recipient,
            global::System.Byte rp_giver, global::System.Byte rp_Archive)
        {
            recipient recipient = new recipient();
            recipient.rp_key = rp_key;
            recipient.rp_lastname = rp_lastname;
            recipient.rp_password = rp_password;
            recipient.rp_background = rp_background;
            recipient.rp_sound = rp_sound;
            recipient.rp_firstname = rp_firstname;
            recipient.rp_email = rp_email;
            recipient.rp_fm_key = rp_fm_key;
            recipient.rp_recipient = rp_recipient;
            recipient.rp_giver = rp_giver;
            recipient.rp_Archive = rp_Archive;
            return recipient;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 rp_key
        {
            get
            {
                return _rp_key;
            }
            set
            {
                if (_rp_key != value)
                {
                    Onrp_keyChanging(value);
                    ReportPropertyChanging("rp_key");
                    _rp_key = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("rp_key");
                    Onrp_keyChanged();
                }
            }
        }
        private global::System.Int32 _rp_key;
        partial void Onrp_keyChanging(global::System.Int32 value);
        partial void Onrp_keyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String rp_lastname
        {
            get
            {
                return _rp_lastname;
            }
            set
            {
                Onrp_lastnameChanging(value);
                ReportPropertyChanging("rp_lastname");
                _rp_lastname = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("rp_lastname");
                Onrp_lastnameChanged();
            }
        }
        private global::System.String _rp_lastname;
        partial void Onrp_lastnameChanging(global::System.String value);
        partial void Onrp_lastnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String rp_password
        {
            get
            {
                return _rp_password;
            }
            set
            {
                Onrp_passwordChanging(value);
                ReportPropertyChanging("rp_password");
                _rp_password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("rp_password");
                Onrp_passwordChanged();
            }
        }
        private global::System.String _rp_password;
        partial void Onrp_passwordChanging(global::System.String value);
        partial void Onrp_passwordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String rp_background
        {
            get
            {
                return _rp_background;
            }
            set
            {
                Onrp_backgroundChanging(value);
                ReportPropertyChanging("rp_background");
                _rp_background = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("rp_background");
                Onrp_backgroundChanged();
            }
        }
        private global::System.String _rp_background;
        partial void Onrp_backgroundChanging(global::System.String value);
        partial void Onrp_backgroundChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String rp_sound
        {
            get
            {
                return _rp_sound;
            }
            set
            {
                Onrp_soundChanging(value);
                ReportPropertyChanging("rp_sound");
                _rp_sound = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("rp_sound");
                Onrp_soundChanged();
            }
        }
        private global::System.String _rp_sound;
        partial void Onrp_soundChanging(global::System.String value);
        partial void Onrp_soundChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String rp_firstname
        {
            get
            {
                return _rp_firstname;
            }
            set
            {
                Onrp_firstnameChanging(value);
                ReportPropertyChanging("rp_firstname");
                _rp_firstname = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("rp_firstname");
                Onrp_firstnameChanged();
            }
        }
        private global::System.String _rp_firstname;
        partial void Onrp_firstnameChanging(global::System.String value);
        partial void Onrp_firstnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String rp_email
        {
            get
            {
                return _rp_email;
            }
            set
            {
                Onrp_emailChanging(value);
                ReportPropertyChanging("rp_email");
                _rp_email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("rp_email");
                Onrp_emailChanged();
            }
        }
        private global::System.String _rp_email;
        partial void Onrp_emailChanging(global::System.String value);
        partial void Onrp_emailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 rp_fm_key
        {
            get
            {
                return _rp_fm_key;
            }
            set
            {
                Onrp_fm_keyChanging(value);
                ReportPropertyChanging("rp_fm_key");
                _rp_fm_key = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("rp_fm_key");
                Onrp_fm_keyChanged();
            }
        }
        private global::System.Int32 _rp_fm_key;
        partial void Onrp_fm_keyChanging(global::System.Int32 value);
        partial void Onrp_fm_keyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte rp_recipient
        {
            get
            {
                return _rp_recipient;
            }
            set
            {
                Onrp_recipientChanging(value);
                ReportPropertyChanging("rp_recipient");
                _rp_recipient = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("rp_recipient");
                Onrp_recipientChanged();
            }
        }
        private global::System.Byte _rp_recipient;
        partial void Onrp_recipientChanging(global::System.Byte value);
        partial void Onrp_recipientChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte rp_giver
        {
            get
            {
                return _rp_giver;
            }
            set
            {
                Onrp_giverChanging(value);
                ReportPropertyChanging("rp_giver");
                _rp_giver = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("rp_giver");
                Onrp_giverChanged();
            }
        }

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = false)]
        [DataMemberAttribute()]
        public global::System.Byte rp_Archive {
            get {
                return _rp_Archive;
            }
            set {
                Onrp_ArchiveChanging(value);
                ReportPropertyChanging("rp_Archive");
                _rp_Archive = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("rp_Archive");
                Onrp_ArchiveChanged();
            }
        }

        private global::System.Byte _rp_giver;
        partial void Onrp_giverChanging(global::System.Byte value);
        partial void Onrp_giverChanged();

        private global::System.Byte _rp_Archive;
        partial void Onrp_ArchiveChanging(global::System.Int16 value);
        partial void Onrp_ArchiveChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("xmaslistlegacyModel", "fk_er_rp_key", "EventRecip")]
        public EntityCollection<EventRecip> EventRecips
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<EventRecip>("xmaslistlegacyModel.fk_er_rp_key", "EventRecip");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<EventRecip>("xmaslistlegacyModel.fk_er_rp_key", "EventRecip", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("xmaslistlegacyModel", "fk_rp_fm_key", "Family")]
        public Family Family
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Family>("xmaslistlegacyModel.fk_rp_fm_key", "Family").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Family>("xmaslistlegacyModel.fk_rp_fm_key", "Family").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Family> FamilyReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Family>("xmaslistlegacyModel.fk_rp_fm_key", "Family");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Family>("xmaslistlegacyModel.fk_rp_fm_key", "Family", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("xmaslistlegacyModel", "fk_ll_rp_key", "LogonLog")]
        public EntityCollection<LogonLog> LogonLog
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<LogonLog>("xmaslistlegacyModel.fk_ll_rp_key", "LogonLog");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<LogonLog>("xmaslistlegacyModel.fk_ll_rp_key", "LogonLog", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("xmaslistlegacyModel", "fk_li_Author", "lists")]
        public EntityCollection<lists> lists
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<lists>("xmaslistlegacyModel.fk_li_Author", "lists");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<lists>("xmaslistlegacyModel.fk_li_Author", "lists", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("xmaslistlegacyModel", "fk_li_HideFrom", "lists")]
        public EntityCollection<lists> lists1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<lists>("xmaslistlegacyModel.fk_li_HideFrom", "lists");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<lists>("xmaslistlegacyModel.fk_li_HideFrom", "lists", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("xmaslistlegacyModel", "fk_li_rp_key", "lists")]
        public EntityCollection<lists> lists2
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<lists>("xmaslistlegacyModel.fk_li_rp_key", "lists");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<lists>("xmaslistlegacyModel.fk_li_rp_key", "lists", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("xmaslistlegacyModel", "fk_li_takenby", "lists")]
        public EntityCollection<lists> lists3
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<lists>("xmaslistlegacyModel.fk_li_takenby", "lists");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<lists>("xmaslistlegacyModel.fk_li_takenby", "lists", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="xmaslistlegacyModel", Name="theme")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class theme : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new theme object.
        /// </summary>
        /// <param name="tm_key">Initial value of the tm_key property.</param>
        /// <param name="tm_name">Initial value of the tm_name property.</param>
        /// <param name="tm_sound">Initial value of the tm_sound property.</param>
        /// <param name="tm_topimage">Initial value of the tm_topimage property.</param>
        /// <param name="tm_bordercolor">Initial value of the tm_bordercolor property.</param>
        /// <param name="tm_bordercolorlight">Initial value of the tm_bordercolorlight property.</param>
        /// <param name="tm_bordercolordark">Initial value of the tm_bordercolordark property.</param>
        /// <param name="tm_bordersize">Initial value of the tm_bordersize property.</param>
        public static theme Createtheme(global::System.Int32 tm_key, global::System.String tm_name, global::System.String tm_sound, global::System.String tm_topimage, global::System.String tm_bordercolor, global::System.String tm_bordercolorlight, global::System.String tm_bordercolordark, global::System.Int32 tm_bordersize)
        {
            theme theme = new theme();
            theme.tm_key = tm_key;
            theme.tm_name = tm_name;
            theme.tm_sound = tm_sound;
            theme.tm_topimage = tm_topimage;
            theme.tm_bordercolor = tm_bordercolor;
            theme.tm_bordercolorlight = tm_bordercolorlight;
            theme.tm_bordercolordark = tm_bordercolordark;
            theme.tm_bordersize = tm_bordersize;
            return theme;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 tm_key
        {
            get
            {
                return _tm_key;
            }
            set
            {
                if (_tm_key != value)
                {
                    Ontm_keyChanging(value);
                    ReportPropertyChanging("tm_key");
                    _tm_key = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("tm_key");
                    Ontm_keyChanged();
                }
            }
        }
        private global::System.Int32 _tm_key;
        partial void Ontm_keyChanging(global::System.Int32 value);
        partial void Ontm_keyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String tm_name
        {
            get
            {
                return _tm_name;
            }
            set
            {
                Ontm_nameChanging(value);
                ReportPropertyChanging("tm_name");
                _tm_name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("tm_name");
                Ontm_nameChanged();
            }
        }
        private global::System.String _tm_name;
        partial void Ontm_nameChanging(global::System.String value);
        partial void Ontm_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String tm_sound
        {
            get
            {
                return _tm_sound;
            }
            set
            {
                Ontm_soundChanging(value);
                ReportPropertyChanging("tm_sound");
                _tm_sound = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("tm_sound");
                Ontm_soundChanged();
            }
        }
        private global::System.String _tm_sound;
        partial void Ontm_soundChanging(global::System.String value);
        partial void Ontm_soundChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String tm_topimage
        {
            get
            {
                return _tm_topimage;
            }
            set
            {
                Ontm_topimageChanging(value);
                ReportPropertyChanging("tm_topimage");
                _tm_topimage = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("tm_topimage");
                Ontm_topimageChanged();
            }
        }
        private global::System.String _tm_topimage;
        partial void Ontm_topimageChanging(global::System.String value);
        partial void Ontm_topimageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String tm_bordercolor
        {
            get
            {
                return _tm_bordercolor;
            }
            set
            {
                Ontm_bordercolorChanging(value);
                ReportPropertyChanging("tm_bordercolor");
                _tm_bordercolor = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("tm_bordercolor");
                Ontm_bordercolorChanged();
            }
        }
        private global::System.String _tm_bordercolor;
        partial void Ontm_bordercolorChanging(global::System.String value);
        partial void Ontm_bordercolorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String tm_bordercolorlight
        {
            get
            {
                return _tm_bordercolorlight;
            }
            set
            {
                Ontm_bordercolorlightChanging(value);
                ReportPropertyChanging("tm_bordercolorlight");
                _tm_bordercolorlight = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("tm_bordercolorlight");
                Ontm_bordercolorlightChanged();
            }
        }
        private global::System.String _tm_bordercolorlight;
        partial void Ontm_bordercolorlightChanging(global::System.String value);
        partial void Ontm_bordercolorlightChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String tm_bordercolordark
        {
            get
            {
                return _tm_bordercolordark;
            }
            set
            {
                Ontm_bordercolordarkChanging(value);
                ReportPropertyChanging("tm_bordercolordark");
                _tm_bordercolordark = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("tm_bordercolordark");
                Ontm_bordercolordarkChanged();
            }
        }
        private global::System.String _tm_bordercolordark;
        partial void Ontm_bordercolordarkChanging(global::System.String value);
        partial void Ontm_bordercolordarkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 tm_bordersize
        {
            get
            {
                return _tm_bordersize;
            }
            set
            {
                Ontm_bordersizeChanging(value);
                ReportPropertyChanging("tm_bordersize");
                _tm_bordersize = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("tm_bordersize");
                Ontm_bordersizeChanged();
            }
        }
        private global::System.Int32 _tm_bordersize;
        partial void Ontm_bordersizeChanging(global::System.Int32 value);
        partial void Ontm_bordersizeChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("xmaslistlegacyModel", "fk_ev_tm_key", "Event")]
        public EntityCollection<Event> Events
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Event>("xmaslistlegacyModel.fk_ev_tm_key", "Event");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Event>("xmaslistlegacyModel.fk_ev_tm_key", "Event", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
